### PR TITLE
fetch non sql commands results (describe, show)

### PR DESCRIPTION
**Pull request by pysalt**
i found the reason why the fetch command returns `None` for these expressions:  'SHOW', 'DESCRIBE'.
This happens because the library `sqlparse` does not know that this command is a DML-command in clickhouse.
`statement.get_type()` return `'UNKNOWN'` for this commands and self.fetch() return None (because flag need_fetch will set to False in this case).
```
statement = sqlparse.parse(query)[0]
statement_type = statement.get_type()
if statement_type in ('SELECT', 'SHOW', 'DESCRIBE', 'EXISTS'):
    need_fetch = True
else:
    need_fetch = False
```
In my MR i fixed it

### CODE REVIEW

**Comment by maxifom** [comment]
I see that travis is failing. Also I guess if you write some tests it would be perfect MR

**Comment by pysalt** [comment]
All tests are passed. Travis failed on check_format. Ok, i will fix it

**Comment by maxifom** [comment]
About tests: I meant it would be nice if you add your own tests for this cases (show tables, etc) that you fix @pysalt

**Comment by pysalt** [comment]
@maxifom @maximdanilchenko I added tests and fixed formatting =)

**Comment by pysalt** [comment]
After merge you can close this issues:
https://github.com/maximdanilchenko/aiochclient/issues/27
https://github.com/maximdanilchenko/aiochclient/issues/23

**Comment by pysalt** [comment]
@maximdanilchenko Are you alive?)

**Comment by maximdanilchenko** [comment]
@pysalt Thank you for your contribution! Sorry, I was ill for a while, but now I'm better and alive:)
And thank you for adding tests and fixing formatting!

**Comment by pysalt** [comment]
@maximdanilchenko Get well!
I am glad to help you)
We are actively using your project. And i hope it doesnt get sick )

**Pull request merged**
