### PR TITLE
Added JSON inserting by row

### PR DESCRIPTION
**Pull request by fibersel**
*Добавлена возможность вставки записей в формате JSON.Вставка осуществляется по логике, работающей с запросом вида `INSERT INTO table FORMAT JSONEachRow {"record": 0},{"record": 1} `

### CODE REVIEW

**Comment by maximdanilchenko** [comment]
@fibersel, thank you for contribution! 

What's the propose of this feature? 
It will be less effective - a lot of `dumps` calls (one for each row) and a huge request body size increase. If you did it for ability to use `**kwargs` in insert queries, I think in that case it's be better to use **TSVWithNames** (Take names from first dict keys and use only values from another dicts).

**JSONEachRow** is good if you want to make it possible to insert already dumped json - it can be useful. In that case I think it will be good to make an optional enum argument about insert format. Smth like this:
```python
await client.execute(
    "INSERT INTO table VALUES",
    json_string1,  # <- Already dumped json
    json_string2,
    format=JSON_FORMAT
)
```

Also, after all you have to add some tests.

P.S. Please use english :)

**Comment by fibersel** [comment]
I can not use **TSVWithNames**, because records in one buffer may have different set of fields, for example: {"record": 0, "extra_field_1": 1}, {"record": 1}.**JSONEachRow** allows inserting this records.

**Comment by maximdanilchenko** [comment]
Ok, I get it! So you need to do this:

1. Rewrite `json2ch` function. This will be way faster:
```python
def json2ch(*records):
    return dumps(records)[1:-1]
```
2. Add tests.

After that I will merge this MR.
 
Later I will add optional `format` param, optional `str` type of parameters (it is useful when args are already dumped or when user wants to use some custom json encoder (orjson/ujson)) and support of this feature in Cython extension.

**Comment by fibersel** [comment]
some tests are failing because of WITH TOTAL statement

**Comment by maximdanilchenko** [comment]
@fibersel, thank you for fixing tests with aggregation funcs.

**Pull request merged**
